# Generated by Django 5.1.6 on 2025-02-26 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_chat_client_id_remove_chat_freelancer_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
